Client: fix build error in `UnixSSLStream`
Fix the following build error:
```
====================[ Build | ClientSSL.test | Debug ]==========================
"/Users/georgiy.lebedev/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-2/231.8109.222/CLion.app/Contents/bin/cmake/mac/bin/cmake" --build /Users/georgiy.lebedev/Work/tntcxx/build-debug --target ClientSSL.test -j 6
[0/1] Re-running CMake...
-- Build type: Debug
-- OpenSSL 3.1.2 found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/georgiy.lebedev/Work/tntcxx/build-debug
[1/2] Building CXX object CMakeFiles/ClientSSL.test.dir/test/ClientTest.cpp.o
FAILED: CMakeFiles/ClientSSL.test.dir/test/ClientTest.cpp.o
ccache /usr/bin/clang++ -DTNTCXX_ENABLE_SSL -I/usr/local/Cellar/openssl@3/3.1.2/include -I/Users/georgiy.lebedev/Work/tntcxx/. -I/Users/georgiy.lebedev/Work/tntcxx/./src -I/Users/georgiy.lebedev/Work/tntcxx/./third_party/libev -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -fcolor-diagnostics -Wall -Wextra -Werror -std=gnu++17 -MD -MT CMakeFiles/ClientSSL.test.dir/test/ClientTest.cpp.o -MF CMakeFiles/ClientSSL.test.dir/test/ClientTest.cpp.o.d -o CMakeFiles/ClientSSL.test.dir/test/ClientTest.cpp.o -c /Users/georgiy.lebedev/Work/tntcxx/test/ClientTest.cpp
In file included from /Users/georgiy.lebedev/Work/tntcxx/test/ClientTest.cpp:36:
In file included from /Users/georgiy.lebedev/Work/tntcxx/test/../src/Client/Connector.hpp:35:
/Users/georgiy.lebedev/Work/tntcxx/./src/../src/Client/UnixSSLStream.hpp:338:16: error: function previously declared with an explicit exception specification redeclared with an implicit exception specification [-Werror,-Wimplicit-exception-spec-mismatch]
UnixSSLStream::~UnixSSLStream()
               ^
/Users/georgiy.lebedev/Work/tntcxx/./src/../src/Client/UnixSSLStream.hpp:102:9: note: previous declaration is here
        inline ~UnixSSLStream() noexcept;
               ^
1 error generated.
ninja: build stopped: subcommand failed.
```

Declaring a destructor `noexcept` is obviously redundant, since a destructor
is always implicitly `noexcept`.

Needed for #49
Needed for #50